import type { Metadata } from 'next';
import '@/shared/common/main-split.scss';

import { menu } from '@/shared/lib/menu/menu';
import MainNavigation from '@/components/Molecules/MainNavigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <MainNavigation menu={menu} />
        <>{children}</>
      </body>
    </html>
  );
}
